var surveyVersion=4;

var surveyTitle={
	en:'Possibilities For Learning - Survey',
	fr:'something cool in french'
};

var surveyRatings=[
	{id:0, label:{en:'Strongly agree', fr:'tout à fait d\'accord'}, abrv:{en:'SA', fr:'TA'}	 },
	{id:1, label:{en:'Agree',fr:'d\'accord'}, abrv:{en:'A', fr:'DA'}	 },
	{id:2, label:{en:'Neither agree nor disagree', fr:'Ni d\'accord ni en désaccord'}, abrv:{en:'N', fr:'N'}	 },
	{id:3, label:{en:'Disagree', fr:'Désaccord'}, abrv:{en:'D', fr:'D'}	 },
	{id:4, label:{en:'Strongly Disagree', fr:'Fortement en désaccord'}, abrv:{en:'SD', fr:'FD'}	 }	
];

var navMessages={
	partContinue:{en:'Continue', fr:'Continuer'},
	partIncomplete:{en:'One or more parts of this form are not complete. Please make sure all items with a red * have been filled in.', fr:'Une ou plusieurs parties de ce formulaire ne sont pas complètes. S\'il vous plaît assurez-vous que tous les éléments avec un rouge * ont été remplis.'},
	partCompletion:{en:'You have completed this part of the Possibilities For Learning Survey.', fr:'Vous avez terminé cette partie du sondage Possibilités d\'apprentissage.'},
	selected:{en:'Selected', fr:'Choisi'}, 
	back:{en:'Back',fr:'Arrière'},
	next:{en:'Next',fr:'Prochain'},
};

var favNumErrorMessages={
	e0:{en:'Please enter your selection in the empty box.', fr:'Veuillez entrer une question plus ou moins préférée'},
	e1:{en:'You\'ve chosen a number that is not in this section.', fr:'Les questions choisies ne sont pas dans cette section'},
	e2:{en:'The same number cannot be used twice.', fr:'Le même numéro ne peut pas être utilisé deux fois'}	
};

var pflSurvey=[
	{
		version:4,
		partId:0, 
		partType:'INFO',
		partTitle: {en:'My Info', fr:'My Info in fr' },
		partShortTitle: {en:'My Info', fr:'Mon Info' },
		infoFields:[
			{id:0,type:'text',  label:{en:'Name', fr:'Nom'}, data:null},
			{id:1,type:'number', label:{en:'Age', fr:'Âge'}, data:null },
			{id:2,type:'number', label:{en:'Grade', fr:'Année scolaire'}, data:null },
			{id:3,type:'text',  label:{en:'Date', fr:'Date'}, data:null }
		],
		subjectsLabel:{
			label:{en:'My favourite Subject', fr:'Ma matière préférée'}
		},
		subjects:[
			{id:0,label:{en:'Math', fr:'Les mathématiques'} }, 
			{id:1,label:{en:'Reading', fr:'Les mathématiques'} }, 
			{id:2,label:{en:'Writing', fr:'Les mathématiques'} }, 
			{id:3,label:{en:'Science', fr:'Les mathématiques'} }, 
			{id:4,label:{en:'Social Studies', fr:'Les mathématiques'} }, 
			{id:5,label:{en:'Other', fr:'Les mathématiques'} }, 
		],
		selectedSubjectId:null, 
		otherSubjectText:null,
		isComplete:false
	},
	{
		version:4,
		partId:1, 
		partType:'QUESTION',		
		partTitle: {en:'PART ONE: SETTINGS FOR LEARNING', fr:'SECTION UN : CONDITIONS D\'APPRENTISSAGE' },
		partShortTitle: {en:'Part #1', fr:'Partie 1' },
		partInfo:{
			en: 'This part of the form is about the places, people and things you like to have around you while you are learning your favourite subject. Always think about the school subject you said was your FAVOURITE when you are rating the sentences in all parts of this form. Use the letters to show how much you agree with each sentence:',
			fr:'stuff and things'
		},
		questionIndex:{start:1, end:37},
		questions:[
			{id:1, text:{en:'I like doing projects in a group when I get to choose my group.', fr:'stuff and things'}, selection:null},
			{id:2, text:{en:'I like doing projects in a group when my teacher assigns us to groups.', fr:'stuff and things'}, selection:null },
			{id:3, text:{en:'When I\'m working in a group, I like working with others who learn slower than I do.', fr:'stuff and things'}, selection:null },
			{id:4, text:{en:'When I\'m working in a group, I like working with others who learn at the same speed as I do.', fr:'stuff and things'}, selection:null },
			{id:5, text:{en:'When I\'m working in a group, I like working with others who learn faster than I do.', fr:'stuff and things'}, selection:null },
			{id:6, text:{en:'When I am working with a partner, I like having a partner who learns slower than I do.', fr:'stuff and things'}, selection:null },
			{id:7, text:{en:'When I am working with a partner, I like having a partner who learns as quickly as I do.', fr:'stuff and things'}, selection:null },
			{id:8, text:{en:'When I\'m working with a partner, I like having a partner who learns faster than I do.', fr:'stuff and things'}, selection:null },
			{id:9, text:{en:'I like doing projects with a partner when I get to choose my partner.', fr:'stuff and things'}, selection:null },
			{id:10, text:{en:'I like doing projects with a partner when my teacher assigns me a partner.', fr:'stuff and things'}, selection:null },
			{id:11, text:{en:'	I only like to work in groups.', fr:'stuff and things'}, selection:null },
			{id:12, text:{en:'	I like it when my teacher tries to understand what I\'m trying to say or what I\'m feeling.', fr:'stuff and things'}, selection:null },
			{id:13, text:{en:'	I like it when my teacher gives me time to think after giving me a really difficult idea to understand or a problem to solve.', fr:'stuff and things'}, selection:null },
			{id:14, text:{en:'	I like to ask for extra help.', fr:'stuff and things'}, selection:null },
			{id:15, text:{en:'	I like learning with the same materials, tools or skills that experts use in their work.', fr:'stuff and things'}, selection:null },
			{id:16, text:{en:'	I like learning from textbooks.', fr:'stuff and things'}, selection:null },
			{id:17, text:{en:'	I like to teach my classmates.', fr:'stuff and things'}, selection:null},
			{id:18, text:{en:'	I like to teach children who are younger than me.', fr:'stuff and things'}, selection:null },
			{id:19, text:{en:'	I like having my classmates teach me.', fr:'stuff and things'}, selection:null },
			{id:20, text:{en:'	I like it when my teacher changes the schedule so the whole class can keep working on something fascinating or stop working on something boring.', fr:'stuff and things'}, selection:null },
			{id:21, text:{en:'	I like visiting places outside of school where people are doing work that uses my favourite school subject.', fr:'stuff and things'}, selection:null },
			{id:22, text:{en:'	I like being able to move around my classroom or school while I\'m learning.', fr:'stuff and things'}, selection:null },
			{id:23, text:{en:'	I like learning centres.', fr:'stuff and things'}, selection:null },
			{id:24, text:{en:'	I like to work alone on big projects.', fr:'stuff and things'}, selection:null },
			{id:25, text:{en:'	I like to work on my assignments until I want to stop. It might be longer or shorter than the time allowed in our timetable.', fr:'stuff and things'}, selection:null },
			{id:26, text:{en:'	I like my teacher to tell me what to do on big projects.', fr:'stuff and things'}, selection:null },
			{id:27, text:{en:'	I like it when my teacher lets me stay on an interesting topic even if it is different from the work that the rest of the class is doing.', fr:'stuff and things'}, selection:null },
			{id:28, text:{en:'I like it when my teacher encourages me to try a new way of doing something, even if it sounds weird.', fr:'stuff and things'}, selection:null },
			{id:29, text:{en:'	I like to try to understand things by listening to experts.', fr:'stuff and things'}, selection:null },
			{id:30, text:{en:'	I like to try to understand things by talking with experts.', fr:'stuff and things'}, selection:null },
			
			{id:31, text:{en:'	I like to use the internet to explore my favourite subject.', fr:'stuff and things'}, selection:null },			
			{id:32, text:{en:'	I like to listen in group discussions.', fr:'stuff and things'}, selection:null },
			{id:33, text:{en:'	I like to talk in group discussions.', fr:'stuff and things'}, selection:null },
			{id:34, text:{en:'	I like sitting with my desk in a group with other students.', fr:'stuff and things'}, selection:null },
			{id:35, text:{en:'	I like sitting alone.', fr:'stuff and things'}, selection:null },
			{id:36, text:{en:'	I like sitting with our desks in rows.', fr:'stuff and things'}, selection:null },
			{id:37, text:{en:'	I like sitting away from everyone so I can have my privacy.', fr:'stuff and things'}, selection:null },			
		],
		favorites:{
			title:{en:'Choose from the sentences numbered from ', fr:'stuff and things'},
			most:{label:{en:'Which two things in this section do you like most? ', fr:'stuff and things'}, data:{a:null, b:null }}, 
			least:{label:{en:'Which two things in this section do you like least?', fr:'stuff and things'}, data:{a:null, b:null }}
		},
		isComplete:false
	},
	{
		version:4,
		partId:2, 
		partType:'QUESTION',				
		partTitle: {en:'PART TWO: IDEAS TO LEARN', fr:'SECTION DU : Stuff et things' },
		partShortTitle: {en:'Part #2', fr:'Partie 2' },
		partInfo:{
			en: 'This part of the form is about the kinds of ideas you like to think about in your favourite subject. Remember to think of the school subject you said was your favourite when you are rating the sentences',
			fr:'stuff and things'
		},
		questionIndex:{start:38, end:50},
		questions:[
			{id:1, text:{en:'	I like to learn with words (reading, writing, listening, speaking).', fr:'stuff and things'}, selection:null},
			{id:2, text:{en:'	I like to learn with numbers and mathematical ideas.', fr:'stuff and things'}, selection:null },
			{id:3, text:{en:'	I like to learn with and about musical ideas.', fr:'stuff and things'}, selection:null },
			{id:4, text:{en:'	I like to learn from pictures and drawings.', fr:'stuff and things'}, selection:null },
			{id:5, text:{en:'	I like learning facts and small bits of information.', fr:'stuff and things'}, selection:null },
			{id:6, text:{en:'	I like understanding complicated ideas and problems.', fr:'stuff and things'}, selection:null },
			{id:7, text:{en:'	I like understanding the ways ideas are connected to each other.', fr:'stuff and things'}, selection:null },
			{id:8, text:{en:'	I need to understand how and why things happen.', fr:'stuff and things'}, selection:null },
			{id:9, text:{en:'	I like learning about weird topics and things that I wonder about.', fr:'stuff and things'}, selection:null },
			{id:10, text:{en:'	I like learning about people\'s feelings.', fr:'stuff and things'}, selection:null },
			{id:11, text:{en:'	I like learning about the lives of people who have accomplished great things using my favourite school subject. They could be famous now or famous in the past.', fr:'stuff and things'}, selection:null },
			{id:12, text:{en:'	I like learning how to use my favourite school subject to solve REAL problems.', fr:'stuff and things'}, selection:null },
			{id:13, text:{en:'	I like learning about topics I choose. It might be anything!', fr:'stuff and things'}, selection:null },
		],
		favorites:{
			title:{en:'Choose from the sentences numbered from ', fr:'stuff and things'},
			most:{label:{en:'Which two things in this section do you like most? ', fr:'stuff and things'}, data:{a:null, b:null }}, 
			least:{label:{en:'Which two things in this section do you like least?', fr:'stuff and things'}, data:{a:null, b:null }}
		},
		isComplete:false
	},		
	{
		version:4,		
		partId:3, 
		partType:'QUESTION',				
		partTitle: {en:'PART THREE: WAYS TO LEARN', fr:'SECTION TOIS : Stuff et things part 3!!!!' },
		partShortTitle: {en:'Part #3', fr:'Partie 3' },
		partInfo:{
			en: 'This part of the form is about ways you might like to think and work while you are learning your favourite subject.',
			fr:'stuff and things in french for part 3'
		},
		questionIndex:{start:51, end:74},
		questions:[
			{id:1, text:{en:'	I like finding creative solutions to hard or weird problems.', fr:'stuff and things'}, selection:null},
			{id:2, text:{en:'	I like taking apart (analyzing) big problems or ideas.', fr:'stuff and things'}, selection:null },
			{id:3, text:{en:'	I like to look at familiar things in new ways.', fr:'stuff and things'}, selection:null },
			{id:4, text:{en:'	I like doing things the way experts do them.', fr:'stuff and things'}, selection:null },
			{id:5, text:{en:'	I like to learn from books.', fr:'stuff and things'}, selection:null },
			{id:6, text:{en:'	I like to learn by doing research on my own.', fr:'stuff and things'}, selection:null },
			{id:7, text:{en:'	I like to learn by doing research with help from a teacher.', fr:'stuff and things'}, selection:null },
			{id:8, text:{en:'	I like to learn by doing research with help from an expert who is not my teacher.', fr:'stuff and things'}, selection:null },
			{id:9, text:{en:'	I like experimenting.', fr:'stuff and things'}, selection:null },
			{id:10, text:{en:'	I like doing activities that have more than one right answer and more than one way to find answers.', fr:'stuff and things'}, selection:null },
			{id:11, text:{en:'	I like learning at a slow, easy speed.', fr:'stuff and things'}, selection:null },
			{id:12, text:{en:'	I like learning lots of new ideas quickly.', fr:'stuff and things'}, selection:null },
			{id:13, text:{en:'	I like assignments that can be finished in one class.'}, selection:null },
			{id:14, text:{en:'	I like having lots of time to dig in to ideas and projects.', fr:'stuff and things'}, selection:null },				
			{id:15, text:{en:'	I like learning at my own speed.', fr:'stuff and things'}, selection:null },				
			{id:16, text:{en:'	I like waiting until everyone in my class or group understands the lesson before going on to a new idea.', fr:'stuff and things'}, selection:null },				
			{id:17, text:{en:'	I like thinking about my thinking and the ways my mind works.', fr:'stuff and things'}, selection:null },				
			{id:18, text:{en:'	I like wondering.', fr:'stuff and things'}, selection:null },				
			{id:19, text:{en:'	I like hearing the ways other students are thinking about something I\'m having trouble with.', fr:'stuff and things'}, selection:null },				
			{id:20, text:{en:'	I like explaining my thinking to other students.', fr:'stuff and things'}, selection:null },				
			{id:21, text:{en:'	I like creating pictures in my mind of what I\'m learning.', fr:'stuff and things'}, selection:null },				
			{id:22, text:{en:'	I like having time to think about my ideas before I start to work on an assignment.', fr:'stuff and things'}, selection:null },				
			{id:23, text:{en:'	I like learning when I get to choose the way I\'ll be learning.', fr:'stuff and things'}, selection:null },				
			{id:24, text:{en:'	I like to learn in many different ways.', fr:'stuff and things'}, selection:null },				
		],
		favorites:{
			title:{en:'Choose from the sentences numbered from ', fr:'stuff and things'},
			most:{label:{en:'Which two things in this section do you like most? ', fr:'stuff and things'}, data:{a:null, b:null }}, 
			least:{label:{en:'Which two things in this section do you like least?', fr:'stuff and things'}, data:{a:null, b:null }}
		},
		isComplete:false
	},	
	{
		version:4,		
		partId:4, 
		partType:'QUESTION',				
		partTitle: {en:'PART FOUR: SHOWING YOUR LEARNING', fr:'SECTION FOUR: Stuff et things part 4!!!!' },
		partShortTitle: {en:'Part #4', fr:'Partie 4' },
		partInfo:{
			en: 'This part of the form asks about ways you like to show what you\'ve learned. Keep thinking about the favourite school subject you circled on the first page when you are rating these sentences. ',
			fr:'stuff and things in french for part 5'
		},
		questionIndex:{start:75, end:100},
		questions:[
			{id:1, text:{en:'	I like sharing what I\’m learning with students in my class.', fr:'stuff and things'}, selection:null},
			{id:2, text:{en:'	I like to hear an expert\'s thoughts about my work.', fr:'stuff and things'}, selection:null },
			{id:3, text:{en:'	I like sharing what I\’m learning with younger students.', fr:'stuff and things'}, selection:null },
			{id:4, text:{en:'	I like sharing what I\’m learning with older students.', fr:'stuff and things'}, selection:null },
			{id:5, text:{en:'	I like sharing what I\’m learning with adults outside of school.', fr:'stuff and things'}, selection:null },
			{id:6, text:{en:'	I like sharing what I\’m learning with my family.', fr:'stuff and things'}, selection:null },	
			{id:7, text:{en:'	I like to be able to choose who will hear about or see what I\'ve learned.', fr:'stuff and things'}, selection:null },				
			{id:8, text:{en:'	I like my teacher to tell me how I\'ll be marked before I begin an assignment.', fr:'stuff and things'}, selection:null },
			{id:9, text:{en:'	I like tests.', fr:'stuff and things'}, selection:null },
			{id:10, text:{en:'	I like to mark my own work.', fr:'stuff and things'}, selection:null },
			{id:11, text:{en:'	I like to have my teacher mark my work.', fr:'stuff and things'}, selection:null },
			{id:12, text:{en:'	I like discussing my mark with my teacher.', fr:'stuff and things'}, selection:null },
			{id:13, text:{en:'	I like to have an expert mark my work.', fr:'stuff and things'}, selection:null },
			{id:14, text:{en:'	I like to have one or more of my classmates mark my work.', fr:'stuff and things'}, selection:null },
			{id:15, text:{en:'	I like to have feedback (suggestions) from my teacher that will improve my work before it is ready to be marked.', fr:'stuff and things'}, selection:null },			
			{id:16, text:{en:'	I like to have feedback (suggestions) from my classmates that will improve my work before it is ready to be marked.', fr:'stuff and things'}, selection:null },			
			{id:17, text:{en:'	I like to have my work marked in the same way an expert\'s would be judged.', fr:'stuff and things'}, selection:null },						
			{id:18, text:{en:'	I like to decide how my work will be marked.', fr:'stuff and things'}, selection:null },							
			{id:19, text:{en:'	Before I start working on a project, I like to talk about who will mark it and how it will be marked with my teacher so we can decide together.', fr:'stuff and things'}, selection:null },
			{id:20, text:{en:'	Even when I get a good mark I like hearing about ways it could be improved.', fr:'stuff and things'}, selection:null },				
			{id:21, text:{en:'	I like knowing if my mark is better or worse than my classmates.', fr:'stuff and things'}, selection:null },							
			{id:22, text:{en:'	I like big projects.', fr:'stuff and things'}, selection:null },				
			{id:23, text:{en:'	I like to choose the way I\'ll show what I\'ve learned (in a play, a poster, a report, etc.).', fr:'stuff and things'}, selection:null },				
			{id:24, text:{en:'I like to have my teacher tell me how to show what I have learned (in a play, a poster, a report, etc.).', fr:'stuff and things'}, selection:null },				
			{id:25, text:{en:'I like to change ideas from one form to another, like changing a story into a play or a math problem into music, or writing a poem about a photo.', fr:'stuff and things'}, selection:null },			
			{id:26, text:{en:'	I like to be able to show what I\'ve learned in different ways on different assignments.', fr:'stuff and things'}, selection:null },				
		],
		favorites:{
			title:{en:'Choose from the sentences numbered from ', fr:'stuff and things'},
			most:{label:{en:'Which two things in this section do you like most? ', fr:'stuff and things'}, data:{a:null, b:null }}, 
			least:{label:{en:'Which two things in this section do you like least?', fr:'stuff and things'}, data:{a:null, b:null }}
		},
		isComplete:false
	},
	{
		version:4,		
		partId:5, 
		partType:'LIST',				
		partTitle: {en:'PART FIVE: LISTS OF POSSIBILITIES', fr:'SECTION CINQ: Stuff et things part 5!!!!' },
		partShortTitle: {en:'Part #5', fr:'Partie 5' },
		partInfo:{
			en: 'On each of the next three sections, please choose as many of the things in the lists as you like. ',
			fr:'stuff and things in french for part 5'
		},
		listSections:[
			{
				sectionId:1,
				sectionTitle:{en:'Section 1 - What would you like to learn about?', fr:'Stuff part 1'},
				sectionInfo:{en:'In this list, select any of these things that you would really like to learn about.', fr:'stuff about part 1 in french'},
				sectionItems:[
					{itemId:1, itemText:{en:'animals', fr:'animaux'}, selected:null},
					{itemId:2, itemText:{en:'architecture', fr:'stuff'},selected:null},
					{itemId:3, itemText:{en:'art', fr:'stuff'},selected:null},
					{itemId:4, itemText:{en:'astronomy', fr:'stuff'},selected:null},
					{itemId:5, itemText:{en:'aviation', fr:'stuff'},selected:null},
					{itemId:6, itemText:{en:'beauty', fr:'stuff'},selected:null},
					{itemId:7, itemText:{en:'brains', fr:'stuff'},selected:null},
					{itemId:8, itemText:{en:'building', fr:'stuff'},selected:null},
					{itemId:9, itemText:{en:'business', fr:'stuff'},selected:null},
					{itemId:10, itemText:{en:'calculus', fr:'stuff'},selected:null},					
					{itemId:12, itemText:{en:'change', fr:'stuff'},selected:null},
					{itemId:13, itemText:{en:'chaos', fr:'stuff'},selected:null},
					{itemId:14, itemText:{en:'chaos theory', fr:'stuff'},selected:null},
					{itemId:15, itemText:{en:'chemistry', fr:'stuff'},selected:null},
					{itemId:16, itemText:{en:'comedy', fr:'stuff'},selected:null},
					{itemId:17, itemText:{en:'communication', fr:'stuff'},selected:null},
					{itemId:18, itemText:{en:'conflict', fr:'stuff'},selected:null},
					{itemId:19, itemText:{en:'courage', fr:'stuff'},selected:null},
					{itemId:20, itemText:{en:'crafts', fr:'stuff'},selected:null},
					{itemId:21, itemText:{en:'cultures', fr:'stuff'}, selected:null},
					{itemId:22, itemText:{en:'dancing', fr:'stuff'},selected:null},
					{itemId:23, itemText:{en:'design', fr:'stuff'},selected:null},
					{itemId:24, itemText:{en:'dinosaurs', fr:'stuff'},selected:null},
					{itemId:25, itemText:{en:'drama and acting', fr:'stuff'},selected:null},
					{itemId:26, itemText:{en:'dreams', fr:'stuff'},selected:null},
					{itemId:27, itemText:{en:'ecology', fr:'stuff'},selected:null},
					{itemId:28, itemText:{en:'endangered species', fr:'stuff'},selected:null},
					{itemId:29, itemText:{en:'engineering', fr:'stuff'},selected:null},
					{itemId:30, itemText:{en:'environment', fr:'stuff'},selected:null},
					{itemId:31, itemText:{en:'ethics', fr:'stuff'}, selected:null},
					{itemId:32, itemText:{en:'exploration', fr:'stuff'},selected:null},
					{itemId:33, itemText:{en:'force', fr:'stuff'},selected:null},
					{itemId:34, itemText:{en:'foreign countries', fr:'stuff'},selected:null},
					{itemId:35, itemText:{en:'foreign languages', fr:'stuff'},selected:null},
					{itemId:36, itemText:{en:'fractals', fr:'stuff'},selected:null},
					{itemId:37, itemText:{en:'freedom', fr:'stuff'},selected:null},
					{itemId:38, itemText:{en:'geography', fr:'stuff'},selected:null},
					{itemId:39, itemText:{en:'geology', fr:'stuff'},selected:null},
					{itemId:40, itemText:{en:'geometry', fr:'stuff'},selected:null},
					{itemId:41, itemText:{en:'ghosts', fr:'stuff'}, selected:null},
					{itemId:42, itemText:{en:'government', fr:'stuff'},selected:null},
					{itemId:43, itemText:{en:'history', fr:'stuff'},selected:null},
					{itemId:44, itemText:{en:'human body', fr:'stuff'},selected:null},
					{itemId:45, itemText:{en:'insects', fr:'stuff'},selected:null},
					{itemId:46, itemText:{en:'inventions', fr:'stuff'},selected:null},
					{itemId:47, itemText:{en:'inventors', fr:'stuff'},selected:null},
					{itemId:48, itemText:{en:'justice', fr:'stuff'},selected:null},
					{itemId:49, itemText:{en:'languages', fr:'stuff'},selected:null},
					{itemId:50, itemText:{en:'law', fr:'stuff'},selected:null},
					{itemId:51, itemText:{en:'literature', fr:'stuff'}, selected:null},
					{itemId:52, itemText:{en:'love', fr:'stuff'},selected:null},
					{itemId:53, itemText:{en:'medicine', fr:'stuff'},selected:null},
					{itemId:54, itemText:{en:'meteorology', fr:'stuff'},selected:null},
					{itemId:55, itemText:{en:'money', fr:'stuff'},selected:null},
					{itemId:56, itemText:{en:'music', fr:'stuff'},selected:null},
					{itemId:57, itemText:{en:'mythology', fr:'stuff'},selected:null},
					{itemId:58, itemText:{en:'natural catastrophes', fr:'stuff'},selected:null},
					{itemId:59, itemText:{en:'oceans', fr:'stuff'},selected:null},
					{itemId:60, itemText:{en:'patterns', fr:'stuff'},selected:null},
					{itemId:61, itemText:{en:'peace', fr:'stuff'}, selected:null},
					{itemId:62, itemText:{en:'philosophy', fr:'stuff'},selected:null},
					{itemId:63, itemText:{en:'physics', fr:'stuff'},selected:null},
					{itemId:64, itemText:{en:'poetry', fr:'stuff'},selected:null},
					{itemId:65, itemText:{en:'politics', fr:'stuff'},selected:null},
					{itemId:66, itemText:{en:'power', fr:'stuff'},selected:null},
					{itemId:67, itemText:{en:'psychology', fr:'stuff'},selected:null},
					{itemId:68, itemText:{en:'religion', fr:'stuff'},selected:null},
					{itemId:69, itemText:{en:'robotics', fr:'stuff'},selected:null},
					{itemId:70, itemText:{en:'science fiction', fr:'stuff'},selected:null},
					{itemId:71, itemText:{en:'sculpture', fr:'stuff'}, selected:null},
					{itemId:72, itemText:{en:'sources of energy', fr:'stuff'},selected:null},
					{itemId:73, itemText:{en:'space travel and technology', fr:'stuff'},selected:null},
					{itemId:74, itemText:{en:'sports', fr:'stuff'},selected:null},
					{itemId:75, itemText:{en:'structures', fr:'stuff'},selected:null},
					{itemId:76, itemText:{en:'supernatural events', fr:'stuff'},selected:null},
					{itemId:77, itemText:{en:'systems', fr:'stuff'},selected:null},
					{itemId:78, itemText:{en:'technology', fr:'stuff'},selected:null},
					{itemId:79, itemText:{en:'the future', fr:'stuff'},selected:null},
					{itemId:80, itemText:{en:'the universe', fr:'stuff'},selected:null},					
					{itemId:81, itemText:{en:'theater and acting', fr:'stuff'}, selected:null},
					{itemId:82, itemText:{en:'time', fr:'stuff'},selected:null},
					{itemId:83, itemText:{en:'travel', fr:'stuff'},selected:null},
					{itemId:84, itemText:{en:'TV', fr:'stuff'},selected:null},
					{itemId:85, itemText:{en:'UFOs', fr:'stuff'},selected:null},
					{itemId:86, itemText:{en:'values', fr:'stuff'},selected:null},
					{itemId:87, itemText:{en:'war', fr:'stuff'},selected:null},					
				],
				otherItemsText:{en:'List any other things you\'d like to learn, separate each with a comma', fr:'en francais!'},
				sectionOtherItems:null,
				userQuestionsText:{en:'List any questions that have been on your mind.', fr:'en francais! too!'},
				sectionUserQuestions:null
			},			
			{
				sectionId:2,
				sectionTitle:{en:'Section 2 - In what ways would you like to learn?', fr:'Stuff part 2'},
				sectionInfo:{en:'In this list you\'ll find words that describe ways to learn fascinating things. Select all the ways you like.', fr:'stuff about part 2 in french'},
				sectionItems:[
					{itemId:1, itemText:{en:'adapt', fr:'stuff'},selected:null},
					{itemId:2, itemText:{en:'analyze', fr:'stuff'},selected:null},
					{itemId:3, itemText:{en:'appraise', fr:'stuff'},selected:null},
					{itemId:4, itemText:{en:'arbitrate', fr:'stuff'},selected:null},
					{itemId:5, itemText:{en:'argue', fr:'stuff'},selected:null},
					{itemId:6, itemText:{en:'arrange', fr:'stuff'},selected:null},
					{itemId:7, itemText:{en:'assess', fr:'stuff'},selected:null},
					{itemId:8, itemText:{en:'award', fr:'stuff'},selected:null},
					{itemId:9, itemText:{en:'blend', fr:'stuff'},selected:null},
					{itemId:10, itemText:{en:'calculate', fr:'stuff'},selected:null},
					{itemId:11, itemText:{en:'change', fr:'stuff'},selected:null},
					{itemId:12, itemText:{en:'choose', fr:'stuff'},selected:null},
					{itemId:13, itemText:{en:'classify', fr:'stuff'},selected:null},
					{itemId:14, itemText:{en:'collect', fr:'stuff'},selected:null},
					{itemId:15, itemText:{en:'combine', fr:'stuff'},selected:null},
					{itemId:16, itemText:{en:'compare', fr:'stuff'},selected:null},
					{itemId:17, itemText:{en:'compile', fr:'stuff'},selected:null},
					{itemId:18, itemText:{en:'compose', fr:'stuff'},selected:null},
					{itemId:19, itemText:{en:'conclude', fr:'stuff'},selected:null},
					{itemId:20, itemText:{en:'construct', fr:'stuff'},selected:null},
					{itemId:21, itemText:{en:'contrast', fr:'stuff'},selected:null},
					{itemId:22, itemText:{en:'count', fr:'stuff'},selected:null},
					{itemId:23, itemText:{en:'create', fr:'stuff'},selected:null},
					{itemId:24, itemText:{en:'critique', fr:'stuff'},selected:null},
					{itemId:25, itemText:{en:'debate', fr:'stuff'},selected:null},
					{itemId:26, itemText:{en:'decide', fr:'stuff'},selected:null},
					{itemId:27, itemText:{en:'deconstruct', fr:'stuff'},selected:null},
					{itemId:28, itemText:{en:'defend', fr:'stuff'},selected:null},
					{itemId:29, itemText:{en:'define', fr:'stuff'},selected:null},
					{itemId:30, itemText:{en:'demonstrate', fr:'stuff'},selected:null},
					{itemId:31, itemText:{en:'describe', fr:'stuff'},selected:null},
					{itemId:32, itemText:{en:'design', fr:'stuff'},selected:null},
					{itemId:33, itemText:{en:'determine', fr:'stuff'},selected:null},
					{itemId:34, itemText:{en:'develop', fr:'stuff'},selected:null},
					{itemId:35, itemText:{en:'diagram', fr:'stuff'},selected:null},
					{itemId:36, itemText:{en:'differentiate', fr:'stuff'},selected:null},
					{itemId:37, itemText:{en:'discuss', fr:'stuff'},selected:null},
					{itemId:38, itemText:{en:'disprove', fr:'stuff'},selected:null},
					{itemId:39, itemText:{en:'dispute', fr:'stuff'},selected:null},
					{itemId:40, itemText:{en:'dissect', fr:'stuff'},selected:null},
					{itemId:41, itemText:{en:'distinguish', fr:'stuff'},selected:null},
					{itemId:42, itemText:{en:'divide', fr:'stuff'},selected:null},
					{itemId:43, itemText:{en:'elaborate', fr:'stuff'},selected:null},
					{itemId:44, itemText:{en:'estimate', fr:'stuff'},selected:null},
					{itemId:45, itemText:{en:'evaluate', fr:'stuff'},selected:null},
					{itemId:46, itemText:{en:'explain', fr:'stuff'},selected:null},
					{itemId:47, itemText:{en:'form', fr:'stuff'},selected:null},
					{itemId:48, itemText:{en:'formulate', fr:'stuff'},selected:null},
					{itemId:49, itemText:{en:'grade', fr:'stuff'},selected:null},
					{itemId:50, itemText:{en:'group', fr:'stuff'},selected:null},
					{itemId:51, itemText:{en:'hypothesize', fr:'stuff'},selected:null},
					{itemId:52, itemText:{en:'illustrate', fr:'stuff'},selected:null},
					{itemId:53, itemText:{en:'imagine', fr:'stuff'},selected:null},
					{itemId:54, itemText:{en:'improve', fr:'stuff'},selected:null},
					{itemId:55, itemText:{en:'integrate', fr:'stuff'},selected:null},
					{itemId:56, itemText:{en:'interpret', fr:'stuff'},selected:null},
					{itemId:57, itemText:{en:'invent', fr:'stuff'},selected:null},
					{itemId:58, itemText:{en:'investigate', fr:'stuff'},selected:null},
					{itemId:59, itemText:{en:'judge', fr:'stuff'},selected:null},
					{itemId:60, itemText:{en:'justify', fr:'stuff'},selected:null},
					{itemId:61, itemText:{en:'mediate', fr:'stuff'},selected:null},
					{itemId:62, itemText:{en:'modify', fr:'stuff'},selected:null},
					{itemId:63, itemText:{en:'monitor', fr:'stuff'},selected:null},
					{itemId:64, itemText:{en:'organize', fr:'stuff'},selected:null},
					{itemId:65, itemText:{en:'outline', fr:'stuff'},selected:null},
					{itemId:66, itemText:{en:'paint', fr:'stuff'},selected:null},
					{itemId:67, itemText:{en:'plan', fr:'stuff'},selected:null},
					{itemId:68, itemText:{en:'predict', fr:'stuff'},selected:null},
					{itemId:69, itemText:{en:'prepare', fr:'stuff'},selected:null},
					{itemId:70, itemText:{en:'prioritize', fr:'stuff'},selected:null},
					{itemId:71, itemText:{en:'produce', fr:'stuff'},selected:null},
					{itemId:72, itemText:{en:'propose', fr:'stuff'},selected:null},
					{itemId:73, itemText:{en:'rank', fr:'stuff'},selected:null},
					{itemId:74, itemText:{en:'rate', fr:'stuff'},selected:null},
					{itemId:75, itemText:{en:'recite', fr:'stuff'},selected:null},
					{itemId:76, itemText:{en:'recommend', fr:'stuff'},selected:null},
					{itemId:77, itemText:{en:'relate', fr:'stuff'},selected:null},
					{itemId:78, itemText:{en:'revise', fr:'stuff'},selected:null},
					{itemId:79, itemText:{en:'rewrite', fr:'stuff'},selected:null},
					{itemId:80, itemText:{en:'role-play', fr:'stuff'},selected:null},
					{itemId:81, itemText:{en:'separate', fr:'stuff'},selected:null},
					{itemId:82, itemText:{en:'simplify', fr:'stuff'},selected:null},
					{itemId:83, itemText:{en:'solve', fr:'stuff'},selected:null},
					{itemId:84, itemText:{en:'sort', fr:'stuff'},selected:null},
					{itemId:85, itemText:{en:'strengthen', fr:'stuff'},selected:null},
					{itemId:86, itemText:{en:'summarize', fr:'stuff'},selected:null},
					{itemId:87, itemText:{en:'support', fr:'stuff'},selected:null},
					{itemId:88, itemText:{en:'survey', fr:'stuff'},selected:null},
					{itemId:89, itemText:{en:'synthesize', fr:'stuff'},selected:null},
					{itemId:90, itemText:{en:'test', fr:'stuff'},selected:null},
					{itemId:91, itemText:{en:'track', fr:'stuff'},selected:null},
					{itemId:92, itemText:{en:'verify', fr:'stuff'},selected:null},
					{itemId:93, itemText:{en:'weigh', fr:'stuff'},selected:null},					
				],
				otherItemsText:{en:'Are there other ways you\'d like to learn? List them here, separate each with a comma.', fr:'en francais!'},
				sectionOtherItems:null,
			},						
			{
				sectionId:3,
				sectionTitle:{en:'Section 3 - How would you like to show your learning?', fr:'Stuff part 3'},
				sectionInfo:{en:'This is a list of things you might make to show what you\'ve learned. Select all that look good to you.', fr:'stuff about part 3 in french'},
				sectionItems:[
					{itemId:1, itemText:{en:'3-D model', fr:'stuff'},selected:null},
					{itemId:2, itemText:{en:'advertisement', fr:'stuff'},selected:null},
					{itemId:3, itemText:{en:'amusement park ride', fr:'stuff'},selected:null},
					{itemId:4, itemText:{en:'app', fr:'stuff'},selected:null},
					{itemId:5, itemText:{en:'article for magazine', fr:'stuff'},selected:null},
					{itemId:6, itemText:{en:'autobiography', fr:'stuff'},selected:null},
					{itemId:7, itemText:{en:'banner', fr:'stuff'},selected:null},
					{itemId:8, itemText:{en:'bibliography', fr:'stuff'},selected:null},
					{itemId:9, itemText:{en:'biography', fr:'stuff'},selected:null},
					{itemId:10, itemText:{en:'blog', fr:'stuff'},selected:null},
					{itemId:11, itemText:{en:'blueprint', fr:'stuff'},selected:null},
					{itemId:12, itemText:{en:'book', fr:'stuff'},selected:null},
					{itemId:13, itemText:{en:'book review', fr:'stuff'},selected:null},
					{itemId:14, itemText:{en:'broadcast', fr:'stuff'},selected:null},
					{itemId:15, itemText:{en:'brochure', fr:'stuff'},selected:null},
					{itemId:16, itemText:{en:'business plan', fr:'stuff'},selected:null},
					{itemId:17, itemText:{en:'campaign', fr:'stuff'},selected:null},
					{itemId:18, itemText:{en:'cartoon', fr:'stuff'},selected:null},
					{itemId:19, itemText:{en:'carving', fr:'stuff'},selected:null},
					{itemId:20, itemText:{en:'celebration', fr:'stuff'},selected:null},
					{itemId:21, itemText:{en:'chapter', fr:'stuff'},selected:null},
					{itemId:22, itemText:{en:'chart', fr:'stuff'},selected:null},
					{itemId:23, itemText:{en:'club', fr:'stuff'},selected:null},
					{itemId:24, itemText:{en:'collage', fr:'stuff'},selected:null},
					{itemId:25, itemText:{en:'collection', fr:'stuff'},selected:null},
					{itemId:26, itemText:{en:'comic strip', fr:'stuff'},selected:null},
					{itemId:27, itemText:{en:'commentary', fr:'stuff'},selected:null},
					{itemId:28, itemText:{en:'commercial', fr:'stuff'},selected:null},
					{itemId:29, itemText:{en:'computer graphic', fr:'stuff'},selected:null},
					{itemId:30, itemText:{en:'computer program', fr:'stuff'},selected:null},
					{itemId:31, itemText:{en:'conference presentation', fr:'stuff'},selected:null},
					{itemId:32, itemText:{en:'critical analysis', fr:'stuff'},selected:null},
					{itemId:33, itemText:{en:'dance', fr:'stuff'},selected:null},
					{itemId:34, itemText:{en:'debate', fr:'stuff'},selected:null},
					{itemId:35, itemText:{en:'demonstration', fr:'stuff'},selected:null},
					{itemId:36, itemText:{en:'diagram', fr:'stuff'},selected:null},
					{itemId:37, itemText:{en:'dialogue', fr:'stuff'},selected:null},
					{itemId:38, itemText:{en:'diary', fr:'stuff'},selected:null},
					{itemId:39, itemText:{en:'dictionary', fr:'stuff'},selected:null},
					{itemId:40, itemText:{en:'display', fr:'stuff'},selected:null},
					{itemId:41, itemText:{en:'documentary', fr:'stuff'},selected:null},
					{itemId:42, itemText:{en:'drawing', fr:'stuff'},selected:null},
					{itemId:43, itemText:{en:'editorial', fr:'stuff'},selected:null},
					{itemId:44, itemText:{en:'equation', fr:'stuff'},selected:null},
					{itemId:45, itemText:{en:'essay', fr:'stuff'},selected:null},
					{itemId:46, itemText:{en:'evaluation checklist', fr:'stuff'},selected:null},
					{itemId:47, itemText:{en:'event', fr:'stuff'},selected:null},
					{itemId:48, itemText:{en:'exhibit', fr:'stuff'},selected:null},
					{itemId:49, itemText:{en:'experiment', fr:'stuff'},selected:null},
					{itemId:50, itemText:{en:'fabric', fr:'stuff'},selected:null},
					{itemId:51, itemText:{en:'fact file', fr:'stuff'},selected:null},
					{itemId:52, itemText:{en:'fairy tale', fr:'stuff'},selected:null},
					{itemId:53, itemText:{en:'film or filmstrip', fr:'stuff'},selected:null},
					{itemId:54, itemText:{en:'flag', fr:'stuff'},selected:null},
					{itemId:55, itemText:{en:'floor plan', fr:'stuff'},selected:null},
					{itemId:56, itemText:{en:'flow chart', fr:'stuff'},selected:null},
					{itemId:57, itemText:{en:'flyer', fr:'stuff'},selected:null},
					{itemId:58, itemText:{en:'game', fr:'stuff'},selected:null},
					{itemId:59, itemText:{en:'game show', fr:'stuff'},selected:null},
					{itemId:60, itemText:{en:'geometric model', fr:'stuff'},selected:null},
					{itemId:61, itemText:{en:'graph', fr:'stuff'},selected:null},
					{itemId:62, itemText:{en:'graphic', fr:'stuff'},selected:null},
					{itemId:63, itemText:{en:'graphic organizer', fr:'stuff'},selected:null},
					{itemId:64, itemText:{en:'greeting card', fr:'stuff'},selected:null},
					{itemId:65, itemText:{en:'group presentation', fr:'stuff'},selected:null},
					{itemId:66, itemText:{en:'guide', fr:'stuff'},selected:null},
					{itemId:67, itemText:{en:'handbook', fr:'stuff'},selected:null},
					{itemId:68, itemText:{en:'histogram', fr:'stuff'},selected:null},
					{itemId:69, itemText:{en:'illusion', fr:'stuff'},selected:null},
					{itemId:70, itemText:{en:'illustrated story', fr:'stuff'},selected:null},
					{itemId:71, itemText:{en:'illustration', fr:'stuff'},selected:null},
					{itemId:72, itemText:{en:'instructions', fr:'stuff'},selected:null},
					{itemId:73, itemText:{en:'internet search', fr:'stuff'},selected:null},
					{itemId:74, itemText:{en:'interview', fr:'stuff'},selected:null},
					{itemId:75, itemText:{en:'invention', fr:'stuff'},selected:null},
					{itemId:76, itemText:{en:'investigation', fr:'stuff'},selected:null},
					{itemId:78, itemText:{en:'itinerary', fr:'stuff'},selected:null},
					{itemId:79, itemText:{en:'jewelry', fr:'stuff'},selected:null},
					{itemId:80, itemText:{en:'jingle', fr:'stuff'},selected:null},
					{itemId:81, itemText:{en:'joke', fr:'stuff'},selected:null},
					{itemId:82, itemText:{en:'journal', fr:'stuff'},selected:null},
					{itemId:83, itemText:{en:'learning center', fr:'stuff'},selected:null},
					{itemId:84, itemText:{en:'lecture', fr:'stuff'},selected:null},
					{itemId:85, itemText:{en:'lesson', fr:'stuff'},selected:null},
					{itemId:86, itemText:{en:'letter', fr:'stuff'},selected:null},
					{itemId:87, itemText:{en:'limerick', fr:'stuff'},selected:null},
					{itemId:88, itemText:{en:'log', fr:'stuff'},selected:null},
					{itemId:89, itemText:{en:'logic puzzle', fr:'stuff'},selected:null},
					{itemId:90, itemText:{en:'logo', fr:'stuff'},selected:null},
					{itemId:91, itemText:{en:'machine', fr:'stuff'},selected:null},
					{itemId:92, itemText:{en:'magazine', fr:'stuff'},selected:null},
					{itemId:93, itemText:{en:'magazine article', fr:'stuff'},selected:null},
					{itemId:94, itemText:{en:'manual', fr:'stuff'},selected:null},
					{itemId:95, itemText:{en:'map', fr:'stuff'},selected:null},
					{itemId:96, itemText:{en:'mask', fr:'stuff'},selected:null},
					{itemId:97, itemText:{en:'matrix', fr:'stuff'},selected:null},
					{itemId:98, itemText:{en:'menu', fr:'stuff'},selected:null},
					{itemId:99, itemText:{en:'metaphor', fr:'stuff'},selected:null},
					{itemId:100, itemText:{en:'mobile', fr:'stuff'},selected:null},
					{itemId:101, itemText:{en:'mock trial', fr:'stuff'},selected:null},
					{itemId:102, itemText:{en:'model', fr:'stuff'},selected:null},
					{itemId:103, itemText:{en:'monologue', fr:'stuff'},selected:null},
					{itemId:104, itemText:{en:'montage', fr:'stuff'},selected:null},
					{itemId:105, itemText:{en:'monument', fr:'stuff'},selected:null},
					{itemId:106, itemText:{en:'motto', fr:'stuff'},selected:null},
					{itemId:107, itemText:{en:'multimedia presentation', fr:'stuff'},selected:null},
					{itemId:108, itemText:{en:'mural', fr:'stuff'},selected:null},
					{itemId:109, itemText:{en:'museum', fr:'stuff'},selected:null},
					{itemId:110, itemText:{en:'music', fr:'stuff'},selected:null},
					{itemId:111, itemText:{en:'mystery', fr:'stuff'},selected:null},
					{itemId:112, itemText:{en:'narrative', fr:'stuff'},selected:null},
					{itemId:113, itemText:{en:'news report', fr:'stuff'},selected:null},
					{itemId:114, itemText:{en:'newsletter', fr:'stuff'},selected:null},
					{itemId:115, itemText:{en:'newspaper', fr:'stuff'},selected:null},
					{itemId:116, itemText:{en:'newspaper article', fr:'stuff'},selected:null},
					{itemId:117, itemText:{en:'novel', fr:'stuff'},selected:null},
					{itemId:118, itemText:{en:'oral report', fr:'stuff'},selected:null},
					{itemId:119, itemText:{en:'outline', fr:'stuff'},selected:null},
					{itemId:120, itemText:{en:'painting', fr:'stuff'},selected:null},
					{itemId:121, itemText:{en:'pamphlet', fr:'stuff'},selected:null},
					{itemId:122, itemText:{en:'panel discussion', fr:'stuff'},selected:null},
					{itemId:123, itemText:{en:'pantomime', fr:'stuff'},selected:null},
					{itemId:124, itemText:{en:'party', fr:'stuff'},selected:null},
					{itemId:125, itemText:{en:'pattern', fr:'stuff'},selected:null},
					{itemId:126, itemText:{en:'performance', fr:'stuff'},selected:null},
					{itemId:127, itemText:{en:'personal experience', fr:'stuff'},selected:null},
					{itemId:128, itemText:{en:'photo album', fr:'stuff'},selected:null},
					{itemId:129, itemText:{en:'photo essay', fr:'stuff'},selected:null},
					{itemId:130, itemText:{en:'picture story', fr:'stuff'},selected:null},
					{itemId:131, itemText:{en:'pie chart', fr:'stuff'},selected:null},
					{itemId:132, itemText:{en:'plan', fr:'stuff'},selected:null},
					{itemId:133, itemText:{en:'play', fr:'stuff'},selected:null},
					{itemId:134, itemText:{en:'podcast', fr:'stuff'},selected:null},
					{itemId:135, itemText:{en:'poem', fr:'stuff'},selected:null},
					{itemId:136, itemText:{en:'political cartoon', fr:'stuff'},selected:null},
					{itemId:137, itemText:{en:'pop-up book', fr:'stuff'},selected:null},
					{itemId:138, itemText:{en:'portfolio', fr:'stuff'},selected:null},
					{itemId:139, itemText:{en:'position paper', fr:'stuff'},selected:null},
					{itemId:140, itemText:{en:'poster', fr:'stuff'},selected:null},
					{itemId:141, itemText:{en:'prediction', fr:'stuff'},selected:null},
					{itemId:142, itemText:{en:'presentation', fr:'stuff'},selected:null},
					{itemId:143, itemText:{en:'program', fr:'stuff'},selected:null},
					{itemId:144, itemText:{en:'puppet', fr:'stuff'},selected:null},
					{itemId:145, itemText:{en:'puppet show', fr:'stuff'},selected:null},
					{itemId:146, itemText:{en:'puzzle', fr:'stuff'},selected:null},
					{itemId:147, itemText:{en:'questionnaire', fr:'stuff'},selected:null},
					{itemId:148, itemText:{en:'quilt', fr:'stuff'},selected:null},
					{itemId:149, itemText:{en:'radio show', fr:'stuff'},selected:null},
					{itemId:150, itemText:{en:'rap', fr:'stuff'},selected:null},
					{itemId:151, itemText:{en:'rebus story', fr:'stuff'},selected:null},
					{itemId:152, itemText:{en:'recipe', fr:'stuff'},selected:null},
					{itemId:153, itemText:{en:'recitation', fr:'stuff'},selected:null},
					{itemId:154, itemText:{en:'reenactment', fr:'stuff'},selected:null},
					{itemId:155, itemText:{en:'relief map', fr:'stuff'},selected:null},
					{itemId:156, itemText:{en:'report', fr:'stuff'},selected:null},
					{itemId:157, itemText:{en:'research report', fr:'stuff'},selected:null},
					{itemId:158, itemText:{en:'review', fr:'stuff'},selected:null},
					{itemId:159, itemText:{en:'role play', fr:'stuff'},selected:null},
					{itemId:160, itemText:{en:'samples', fr:'stuff'},selected:null},
					{itemId:161, itemText:{en:'scenario', fr:'stuff'},selected:null},
					{itemId:162, itemText:{en:'science fiction story', fr:'stuff'},selected:null},
					{itemId:163, itemText:{en:'scrapbook', fr:'stuff'},selected:null},
					{itemId:164, itemText:{en:'script', fr:'stuff'},selected:null},
					{itemId:165, itemText:{en:'sculpture', fr:'stuff'},selected:null},
					{itemId:166, itemText:{en:'self-portrait', fr:'stuff'},selected:null},
					{itemId:167, itemText:{en:'seminar', fr:'stuff'},selected:null},
					{itemId:168, itemText:{en:'sermon', fr:'stuff'},selected:null},
					{itemId:169, itemText:{en:'service project', fr:'stuff'},selected:null},
					{itemId:170, itemText:{en:'short story', fr:'stuff'},selected:null},
					{itemId:171, itemText:{en:'sign', fr:'stuff'},selected:null},
					{itemId:172, itemText:{en:'simulation', fr:'stuff'},selected:null},
					{itemId:173, itemText:{en:'sketch', fr:'stuff'},selected:null},
					{itemId:174, itemText:{en:'skit', fr:'stuff'},selected:null},
					{itemId:175, itemText:{en:'slide show', fr:'stuff'},selected:null},
					{itemId:176, itemText:{en:'sociogram', fr:'stuff'},selected:null},
					{itemId:177, itemText:{en:'song', fr:'stuff'},selected:null},
					{itemId:178, itemText:{en:'speech', fr:'stuff'},selected:null},
					{itemId:179, itemText:{en:'spreadsheet', fr:'stuff'},selected:null},
					{itemId:180, itemText:{en:'story', fr:'stuff'},selected:null},
					{itemId:181, itemText:{en:'summary', fr:'stuff'},selected:null},
					{itemId:182, itemText:{en:'survey', fr:'stuff'},selected:null},
					{itemId:183, itemText:{en:'table', fr:'stuff'},selected:null},
					{itemId:184, itemText:{en:'tape-recording', fr:'stuff'},selected:null},
					{itemId:185, itemText:{en:'telegram', fr:'stuff'},selected:null},
					{itemId:186, itemText:{en:'textbook', fr:'stuff'},selected:null},
					{itemId:187, itemText:{en:'theory', fr:'stuff'},selected:null},
					{itemId:188, itemText:{en:'time capsule', fr:'stuff'},selected:null},
					{itemId:189, itemText:{en:'timeline', fr:'stuff'},selected:null},
					{itemId:190, itemText:{en:'trademark', fr:'stuff'},selected:null},
					{itemId:191, itemText:{en:'travelogue', fr:'stuff'},selected:null},
					{itemId:192, itemText:{en:'triptych', fr:'stuff'},selected:null},
					{itemId:193, itemText:{en:'TV show', fr:'stuff'},selected:null},
					{itemId:194, itemText:{en:'Venn diagram', fr:'stuff'},selected:null},
					{itemId:195, itemText:{en:'video game', fr:'stuff'},selected:null},
					{itemId:196, itemText:{en:'wall hanging', fr:'stuff'},selected:null},
					{itemId:197, itemText:{en:'weaving', fr:'stuff'},selected:null},
					{itemId:198, itemText:{en:'webpage', fr:'stuff'},selected:null},
					{itemId:199, itemText:{en:'website', fr:'stuff'},selected:null},
					{itemId:200, itemText:{en:'wiki', fr:'stuff'},selected:null},					
				],
				otherItemsText:{en:'Please list other ways you\'d like to show what you know(separate each with a comma).', fr:'en francais!'},
				sectionOtherItems:null,
			},			
		],
		isComplete:false				
	},
	{
		version:4,		
		partId:6, 
		partType:'DREAM',
		partTitle: {en:'Possibilities For Learning - Dream Sheet', fr:'Feuille de rêve' },
		partShortTitle: {en:'Dream Sheet', fr:'Feuille de rêve' },
		summary:{
			partTitle:{en:'Summary Sheet', fr:'Feuille récapitulative' },
			partTitleDream:{en:'Dream Sheet', fr:'Feuille de rêve' },
			statements:{
				most:{en:'Two MOST FAVOURITE statements from the items in Part', fr:'Deux déclarations les plus FAVOURITES des articles en partie' },
				least:{en:'Two LEAST FAVOURITE statements from the items in Part', fr:'Deux déclarations FAVOURITES MOINS des articles en partie' },
				lists:{
					topics:{en:'Select the topic you like most:', fr:'Sélectionnez deux sujets favoris, un dans chaque liste déroulante' },
					ways:{en:'Select the way to learn you like most:', fr:'Sélectionnez deux façons d\'apprendre dans la liste déroulante' },
					show:{en:'Select the way to show your learning you like most:', fr:'Sélectionnez deux façons préférées de montrer votre apprentissage dans la liste déroulante' },
				},
				listStatements:{
					topics:{en:'Two topics you like most:', fr:'Deux sujets favoris, un dans chaque liste déroulante' },
					ways:{en:'Two ways to learn that you like most:', fr:'Deux façons d\'apprendre dans la liste déroulante' },
					show:{en:'Two ways to show your learning that you like most:', fr:'Deux façons préférées de montrer votre apprentissage dans la liste déroulante' },
				}				
			}
		},
		sections:{
			settingsForLearning:{title:{en:'Selected setting for learning',fr:'Paramètre sélectionné pour l\'apprentissage'}, textVal:null },
			bigIdeas:{title:{en:'Big ideas to learn',fr:'De grandes idées à apprendre'}, textVal:null },
			topic:{title:{en:'Topic',fr:'Sujet'},list:[], textVal:null ,textSummaryVal:null},
			activity:{title:{en:'Activity',fr:'Activité'}, textVal:null },
			action:{title:{en:'Action',fr:'Action'}, list:[],textVal:null,textSummaryVal:null },
			product:{title:{en:'Product',fr:'Produit'},list:[], textVal:null,textSummaryVal:null },
			wayToLearn:{title:{en:'Way to learn',fr:'Façon d\'apprendre'}, textVal:null },
			wayToShowLearning:{title:{en:'Way to show my learning',fr:'Façon de montrer mon apprentissage'}, textVal:null }			
		},
		isComplete:false
		
	},	
];




